spring.application.name=${spring.application.name}

# database Creds--------------------
spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}
spring.datasource.driver-class-name=${spring.datasource.driver-class-name}

spring.jpa.hibernate.ddl-auto=${spring.jpa.hibernate.ddl-auto}
spring.jpa.show-sql=${spring.jpa.show-sql}
spring.jpa.properties.hibernate.dialect=${spring.jpa.properties.hibernate.dialect}

#-----------------------------------

#supabase creds --------------------
supabase.url=${supabase.url}
supabase.key=${supabase.key}
supabase.jwt.secret=${supabase.jwt.secret}
supabase.bucket.name=${supabase.bucket.name}
#-----------------------------------
