spring.application.name=TrainSync

# database Creds--------------------
spring.datasource.url=jdbc:postgresql://db.hmsqhcqnqgbziukpnnku.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=wqDysSep8imypZFp
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#-----------------------------------

#supabase creds --------------------
supabase.url=https://hmsqhcqnqgbziukpnnku.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhtc3FoY3FucWdieml1a3Bubmt1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MjQzODQyNywiZXhwIjoyMDc4MDE0NDI3fQ.dvca0aAtHOoxwcp3xJavVsG9eV79Ic0OSHOpgneRNZE
supabase.jwt.secret=juHHQN3pNlpu4KtiP5KRBM5E7OeN0pfzlIMq3ibLj+qTI+qn5+wPNfH+1Oh7Ef99rMBEG/K4v7YMWSp56XW1mw==
supabase.bucket.name=profile-pictures
#-----------------------------------

#DEFAULT LOGIN FOR TESTING
default.email=sajal147x@gmail.com
default.password=test123