spring.application.name=TrainSync

# Database Config - use Railway environment variables
spring.datasource.url=jdbc:postgresql://turntable.proxy.rlwy.net:16638/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=qyOrjCCcYhGbbUEFWAZCsMRbKldQkovT
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Supabase Config - use environment variables too
supabase.url=https://hmsqhcqnqgbziukpnnku.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhtc3FoY3FucWdieml1a3Bubmt1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MjQzODQyNywiZXhwIjoyMDc4MDE0NDI3fQ.dvca0aAtHOoxwcp3xJavVsG9eV79Ic0OSHOpgneRNZE
supabase.jwt.secret=juHHQN3pNlpu4KtiP5KRBM5E7OeN0pfzlIMq3ibLj+qTI+qn5+wPNfH+1Oh7Ef99rMBEG/K4v7YMWSp56XW1mw==
supabase.bucket.name=profile-pictures

# Default Login for Testing
default.email=${DEFAULT_EMAIL:sajal147x@gmail.com}
default.password=${DEFAULT_PASSWORD:test123}

jwt.secret=F82jd9aD9Kw82lLmF82jd9aD9Kw82lLm

logging.file.name=logs/train-sync.log

logging.level.root=ERROR

#email properties
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=${SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS:true}
